name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout codebase
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . oayanda/continuous_php_image
